### ISSUE TITLE
Regarding HSF

### ISSUE THREAD

**Issue by suhwan-cho** [caoyunkang/AdaCLIP#10]
Hi, thanks a lot for open-sourcing your awesome work! 

I'm really interested in the way you're handling ZSAD by prompting frozen CLIP, but I have some questions about the HSF module.

I noticed that turning off the HSF module (both during training and testing) doesn’t seem to affect performance at all. 

Could you help clarify why that might be the case?

Looking forward to hearing from you!

**Comment by caoyunkang** [comment]
Thanks for your question! I would like to guide you to #9 for a detailed discussion.

**Comment by suhwan-cho** [comment]
Thanks!
