### ISSUE TITLE
if i want The training input data is four channels, because my six-channel data is spliced ​​from six single-channel 2D images. How should I modify the code? I do not have a mask annotation file. Can I use this code?

### ISSUE THREAD

**Issue by watertianyi** [caoyunkang/AdaCLIP#17]

**Comment by caoyunkang** [comment]
hi! You may get two three-channel images from your six inputs, and then add the prediction results of the two together. You may modify the input channel of CLIP, as what [timm](https://timm.fast.ai/models#How-is-timm-able-to-use-pretrained-weights-and-handle-images-that-are-not-3-channel-RGB-images?) does.

In the training process, we need annotated auxiliary data to prompt CLIP, so annotations are required.

**Comment by watertianyi** [comment]
@caoyunkang 
I merged six images with different lighting into six channels

**Comment by watertianyi** [comment]
@caoyunkang 
 I do not have a mask annotation file. Can I use this code?

**Comment by caoyunkang** [comment]
> I do not have a mask annotation file. Can I use this code?

In this case, you may only use the code for inference rather than training with your own data. Just divide the six channels into two 3-channel images, and then you can do the inference.

**Comment by watertianyi** [comment]
> > 我没有掩码注释文件。我可以使用此代码吗？
> 
> 这种情况下，你可能只用代码进行推理，而不是用自己的数据进行训练。只需将六个通道分成两个三通道图像，然后就可以进行推理了。
If it is an RGB three channel, does it also need mask labeling before training?
