### ISSUE TITLE
Poor Localization on MVTEC AD dataset

### ISSUE THREAD

**Issue by rishabh-akridata** [caoyunkang/AdaCLIP#19]
Hello @caoyunkang,
Tried to run the model in ZSAD using the gradio app that you have given on a few mvtec images. However, it is not able to localise the defects when pre-trained dataset is selected as VISA + ClinicDB. However, it is able to localise properly as soon as the pre-trained dataset is selected to MVTECAD + COLONDB. Is this expected? If Yes, any idea how to improve the localization without explicitly fine tuning on the MVTEC dataset?
![image](https://github.com/user-attachments/assets/e7233465-3fea-428f-9fb7-40dc2d8e5d2b)

![image](https://github.com/user-attachments/assets/8a08d713-2fb1-48ee-81c3-75ca6e32ecf3)

![image](https://github.com/user-attachments/assets/5bb0807d-ced0-462a-ae18-a034556c3ac7)

![image](https://github.com/user-attachments/assets/1114fbdf-894a-4cfd-b44c-441e8590bce9)

Thanks.

**Comment by caoyunkang** [comment]
Hi, this is because your given anomalies present to be semantic rather than structural. Semantic anomalies are typically harder to spot without any references, and in comparison, structural anomalies present to have some "high-level similarities", and thus are easier to detect.

**Comment by rishabh-akridata** [comment]
@caoyunkang So the results that are mentioned in the paper regarding the bottle class. Is the model is explicitly trained on mvtec dataset to detect these semantic anomalies?

**Comment by caoyunkang** [comment]
@rishabh-akridata No, we strictly follow the descriptions in our paper, thus, we train on VisA + ColonDB to evaluate the zero-shot performance on MVTec AD. There are also many structural anomalies in the bottle category, so the overall metrics are still good.

**Comment by rishabh-akridata** [comment]
Okay, Thanks.
