### ISSUE TITLE
关于模型文件的保存问题

### ISSUE THREAD

**Issue by LvRenbaba** [caoyunkang/AdaCLIP#22]
作者你好，你们的工作非常具有实际意义！我在使用你们的代码运行的过程中注意到，当测试数据集为HeadCT、BrainMRI和Br35H时，即Image-level时，使用了f1_px作为保存模型的指标，但是在运行时f1_px一直为0，是不是应该使用f1_im作为指标去保存最佳模型文件？

**Comment by caoyunkang** [comment]
我们默认使用Visa作为验证集，因而可以采用pixel-level max_f1作为目标指标。如果你把验证集改为HeadCT等，可以考虑将pixel-level max-F1 改为image-level max-F1用于获取最佳模型。

**Comment by LvRenbaba** [comment]
好的！
