### ISSUE TITLE
Regarding the issue of GPU usage

### ISSUE THREAD

**Issue by magicrane** [caoyunkang/AdaCLIP#23]
Thank you for your excellent work. I would like to know if I can run the experiment with two 2080Ti. If I can, How should I do for training as Out of Memery occured during my repetition

**Comment by caoyunkang** [comment]
You may modify the default setting to ``--prompting_type 'S'`` for a simple try. Enabling dynamic prompting would require more GPU memories.

**Comment by magicrane** [comment]
> You may modify the default setting to `--prompting_type 'S'` for a simple try. Enabling dynamic prompting would require more GPU memories.

Thanks for your reply! I found that batch-size can only be set to 1. If I still don't have enough GPU memory, should I replace it with a card with a larger memory instead of trying to train on two small cards?

**Comment by caoyunkang** [comment]
> Thanks for your reply! I found that batch-size can only be set to 1. If I still don't have enough GPU memory, should I replace it with a card with a larger memory instead of trying to train on two small cards?
> 
> I tried to resize the image to 256 and it worked. It Cost 8033MB

It would be better to use a single GPU with a larger memory.
