### ISSUE TITLE
关于检测结果

### ISSUE THREAD

**Issue by yoho131** [caoyunkang/AdaCLIP#7]
首先感谢开源你们的项目。
我使用你们所提供的预训练权重和[Online Demo](https://huggingface.co/spaces/Caoyunkang/AdaCLIP)分别对同一张数据集内图片进行检测后，发现检测结果差距很大，请问这是为什么呢？
使用预训练权重结果如下
![1723526957317](https://github.com/user-attachments/assets/6e6bde50-211a-4aa8-9ff4-d0bc6deb0cad)
在Online Demo检测结果如下
![image](https://github.com/user-attachments/assets/abc402bc-a315-4c61-86d5-69aa32b47e65)

**Comment by yoho131** [comment]
不好意思 是我理解错了

**Comment by caoyunkang** [comment]
感谢关注 :)

**Comment by Hsuan2021** [comment]
你好，我在测试代码的时候也出现了这样的现象，请问原因是什么呢，我哪里做错了吗？
